# 🎲 GUIDE COMPLET DES MÉTHODES ALÉATOIRES EN PYTHON
Génération de nombres aléatoires : du basique au sécurisé

<div style="background: #f8fafc; padding: 20px; border-radius: 10px; border-left: 5px solid #3b82f6; margin: 20px 0;">

Auteur : FOFANA Lamine
Email : fofanalamine039@gmail.com

GitHub : @fofanalamine
Date : 2026
Version : 1.0

Tags : Python, Random, NumPy, Secrets, Aléatoire, Cryptographie

</div>


📋 Table des Matières
<div style="background: #f0f9ff; padding: 20px; border-radius: 10px; margin: 20px 0;">

🎯 Introduction

🎲 Partie 1 : Module random (Python standard)

📊 Partie 2 : numpy.random (tableaux et performance)

🔐 Partie 3 : Module secrets (sécurité et cryptographie)

⚖️ Comparaison des modules

❓ Bonnes pratiques

</div>



🎯 Introduction
<div style="background: #f0fdf4; padding: 20px; border-radius: 10px; border: 2px solid #86efac; margin: 20px 0;">

La génération de nombres aléatoires est essentielle en Python pour :

les simulations
les jeux
l’analyse de données
la sécurité informatique

Python propose trois approches principales, chacune adaptée à un besoin spécifique.

🎯 Objectifs

✅ Comprendre les différences entre random, numpy.random et secrets
✅ Choisir le bon outil selon le contexte
✅ Générer des valeurs aléatoires efficacement et en toute sécurité

</div>




## 🎲 Partie 1 : Module random standard (Python natif)

📌 Description

Le module random est intégré à Python.
Il permet de générer des nombres pseudo-aléatoires facilement.

✔️ Cas d’usage

- Jeux simples
- Simulations basiques
- Tirages aléatoires

⚠️ Limite

-  Non sécurisé → à éviter pour mots de passe ou tokens



### 1. Fonctions de base pour nombres aléatoires

In [42]:
import random

# 1. random() - Flottant [0.0, 1.0)
x = random.random()  
print("Retourne un flottant entre 0.0 (inclus) et 1.0 (exclus) :",  x)

# 2. uniform(a, b) - Flottant entre a et b (bornes incluses)
x = random.uniform(1.5, 10.5)
print(x)

# 3. randint(a, b) - Entier entre a et b (inclus)
n = random.randint(1, 10)  
print(n)

# 4. randrange([start], stop, [step]) - Comme range() mais aléatoire
a = random.randrange(10)        # 0-9
b = random.randrange(1, 10)     # 1-9
c = random.randrange(0, 100, 5) # 0, 5, 10, ..., 95

print(a)
print(b)
print(c)

Retourne un flottant entre 0.0 (inclus) et 1.0 (exclus) : 0.569104245759145
9.858334402837777
10
0
2
60


### 2. Sélections aléatoires dans des séquences

random.choice(seq)

In [43]:
liste = ['a', 'b', 'c', 'd']
element = random.choice(liste)  # Ex: 'c'
print(element)

chaine = "Bonjour"
lettre = random.choice(chaine)  # Ex: 'o'
print(lettre)

d
o


random.choices(population, weights=None, k=1)

In [44]:
# Avec remise (même élément peut être choisi plusieurs fois)
resultat = random.choices(['a', 'b', 'c'], k=3)  # Ex: ['c', 'c', 'a']
print(resultat)

# Avec pondération
resultat = random.choices(['a', 'b', 'c'], weights=[10, 1, 1], k=4)
# 'a' a 10x plus de chances d'être choisi

print(resultat)

['b', 'c', 'a']
['a', 'c', 'a', 'a']


random.sample(population, k)

In [45]:
# Sans remise (éléments uniques)
resultat = random.sample(range(100), 5)
# Ex: [42, 17, 89, 23, 56] (tous différents)

print(resultat)

[99, 63, 23, 97, 36]


### 3. Mélange et réorganisation

random.shuffle(x)

In [49]:
liste = [1, 2, 3, 4, 5]
random.shuffle(liste)  # Modifie la liste sur place
print(liste)  # Ex: [3, 1, 5, 2, 4]


print()
# Pour obtenir une nouvelle liste mélangée sans modifier l'originale
liste_originale = [1, 2, 3, 4]
liste_melangee = random.sample(liste_originale, len(liste_originale))
print(liste_originale, liste_melangee)

[3, 5, 1, 4, 2]

[1, 2, 3, 4] [4, 2, 1, 3]


### 4. Distributions statistiques

random.normalvariate(mu, sigma) ou gauss(mu, sigma)

In [50]:
# Distribution normale (gaussienne)
# mu = moyenne, sigma = écart-type

x = random.normalvariate(0, 1)  
print(x)

-0.19055441275583185


random.expovariate(lambd)

In [51]:
# Distribution exponentielle

x = random.expovariate(1.5)  # lambda = 1.5
print(x)

1.3278131018575738


### Autres distributions disponibles:

betavariate(alpha, beta) - Distribution Beta

triangular(low, high, mode) - Distribution triangulaire

weibullvariate(alpha, beta) - Distribution Weibull

etc.

In [52]:
# 1. gauss(mu, sigma) / normalvariate(mu, sigma) - Distribution normale
x = random.gauss(0, 1)           # -0.234
x = random.normalvariate(0, 1)   # Même chose
print(f"{x}\n")

# 2. expovariate(lambd) - Distribution exponentielle
x = random.expovariate(1.5)
print(f"{x}\n")

# 3. betavariate(alpha, beta) - Distribution Beta
x = random.betavariate(2, 5)
print(f"{x}\n")

# 4. triangular(low, high, mode) - Distribution triangulaire
x = random.triangular(0, 10, 5)
print(f"{x}\n")

# 5. weibullvariate(alpha, beta) - Distribution Weibull
x = random.weibullvariate(1, 1.5)
print(f"{x}\n")


# 6. paretovariate(alpha) - Distribution Pareto
x = random.paretovariate(1)
print(f"{x}\n")

# 7. lognormvariate(mu, sigma) - Distribution log-normale
x = random.lognormvariate(0, 1)
print(f"{x}\n")

# 8. vonmisesvariate(mu, kappa) - Distribution von Mises
x = random.vonmisesvariate(0, 4)
print(f"{x}\n")

-0.9674337073723389

0.4757384115713226

0.19164675434975217

1.9330763291700914

0.9746112550092013

1.717250892967923

0.3503809486154514

0.5751874700597779



### 5. Contrôle du générateur aléatoire

random.seed(a=None)

In [53]:
# Pour obtenir des résultats reproductibles
random.seed(42)  # Fixe la graine aléatoire
a = random.random()  # Toujours la même valeur avec seed(42)
print(a)


# Utiliser l'heure actuelle par défaut
random.seed()  # Utilise l'heure système

# getstate() / setstate(state) - Sauvegarde/restaure l'état
etat = random.getstate()  # ... opérations ...
# print(etat)

random.setstate(etat)  # Continue la séquence

# getrandbits(k) - Entier avec k bits aléatoires
x = random.getrandbits(8)  # 0-255
print(x)

0.6394267984578837
40


Objet Random()

In [54]:
# Pour créer des générateurs indépendants
gen1 = random.Random(42)
gen2 = random.Random(42)

x = gen1.random()  # Même valeur que y
y = gen2.random()

print(x)
print(y)

0.6394267984578837
0.6394267984578837


### 6. Applications pratiques

Génération de données de test

In [55]:
# Liste aléatoire de nombres
donnees = [random.randint(1, 100) for _ in range(10)]
print(donnees)

print()

# Mot de passe aléatoire
caracteres = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
mot_de_passe = ''.join(random.choices(caracteres, k=12))
print(mot_de_passe)

[41, 10, 10, 84, 7, 85, 24, 2, 37, 33]

!4Xw^g0n&$Qv


Simulation

In [56]:
# Simulation de lancers de dé
def lancer_de():
    return random.randint(1, 6)


# Simulation de 1000 lancers
resultats = [lancer_de() for _ in range(1000)]
print(resultat)

[99, 63, 23, 97, 36]


Échantillonnage statistique

In [82]:
population = list(range(1000))
# print(population)

echantillon = random.sample(population, 100)  # Échantillon de 100 éléments
print(echantillon)

[323, 410, 274, 67, 216, 935, 965, 580, 897, 735, 322, 217, 671, 511, 405, 905, 936, 658, 469, 146, 271, 142, 252, 762, 574, 551, 269, 764, 598, 438, 919, 597, 408, 370, 224, 141, 521, 505, 93, 773, 48, 881, 112, 156, 642, 163, 811, 696, 432, 610, 65, 394, 390, 950, 479, 541, 257, 566, 958, 11, 952, 738, 117, 698, 906, 549, 768, 273, 787, 656, 348, 114, 300, 445, 161, 464, 3, 739, 896, 736, 973, 512, 780, 182, 519, 108, 891, 640, 305, 861, 654, 915, 623, 203, 956, 382, 917, 165, 552, 797]


### 7. Bonnes pratiques et avertissements

1 - Pour la cryptographie, utilisez *secrets* au lieu de *random* :

In [58]:
import secrets
token = secrets.token_hex(16)  # Pour les tokens sécurisés

2 - Reproductibilité :

In [59]:
random.seed(123)  # Pour tests/debug

### 8. Exemple complet récapitulatif

In [60]:
import random

# 1. Initialisation
random.seed(42)  # Pour reproductibilité

# 2. Nombres aléatoires
print("random():", random.random())
print("randint(1, 10):", random.randint(1, 10))
print("uniform(5, 15):", round(random.uniform(5, 15), 2))

# 3. Sélections
liste = ["rouge", "vert", "bleu", "jaune"]
print("choice:", random.choice(liste))
print("sample(2):", random.sample(liste, 2))
print("choices(3):", random.choices(liste, k=3))

# 4. Mélange
cartes = list(range(1, 11)) + ["Valet", "Dame", "Roi"]
random.shuffle(cartes)
print("Cartes mélangées:", cartes[:5])

# 5. Distribution normale
print("Normal(0,1):", round(random.normalvariate(0, 1), 3))

random(): 0.6394267984578837
randint(1, 10): 1
uniform(5, 15): 12.42
choice: vert
sample(2): ['vert', 'rouge']
choices(3): ['bleu', 'bleu', 'jaune']
Cartes mélangées: [6, 4, 3, 9, 5]
Normal(0,1): 1.241


# ______________________________________________________________


## 📊 Partie 2 : numpy.random (pour les tableaux)

📌 Description

Le module numpy.random appartient à NumPy.
Il est optimisé pour manipuler des grandes quantités de données.

✔️ Cas d’usage

- Data science
- Machine learning
- Simulation massive

💡 Avantages
- Très rapide
- Génère des tableaux directement
- Nombreuses distributions statistiques

In [61]:
import numpy as np

# Génération de tableaux aléatoires

# 1. rand(d0, d1, ..., dn) - Tableau de flottants [0, 1)
arr1 = np.random.rand(3, 3)  # Matrice 3x3
print(arr1)

print()
# 2. randn(d0, d1, ..., dn) - Distribution normale standard (moyenne 0, écart-type 1)
arr2 = np.random.randn(2, 4)  
print(arr2)

print()
# 3. randint(low, high=None, size=None) - Entiers aléatoires
arr3 = np.random.randint(0, 10, size=(3, 3))  # Matrice 3x3 d'entiers 0-9
print(arr3)


print()
# 4. random(size=None) - Similaire à rand() mais avec size
arr4 = np.random.random((2, 3))  # Matrice 2x3
print(arr4)


print()
# 5. uniform(low=0.0, high=1.0, size=None) - Distribution uniforme
arr5 = np.random.uniform(-1, 1, size=10)
print(arr5)

[[0.29800523 0.74975513 0.87211448]
 [0.8874296  0.69113541 0.22397289]
 [0.26455287 0.36716967 0.7191017 ]]

[[-2.75267589  1.15958115 -0.63289658  0.01230977]
 [ 0.11546178 -1.41743951  0.01928991  1.56071946]]

[[7 9 8]
 [7 7 5]
 [1 0 6]]

[[0.9949815  0.40002812 0.47615977]
 [0.06127733 0.69096506 0.79988921]]

[-0.48014086 -0.01941747  0.44252233 -0.0359831   0.19248696 -0.62491245
 -0.99305739  0.48310954  0.98095097 -0.87551905]


In [62]:

# 6. normal(loc=0.0, scale=1.0, size=None) - Distribution normale
arr6 = np.random.normal(10, 2, size=100)  # Moyenne=10, écart-type=2
print(arr6)

[11.47976464 12.00108479 10.49872114 12.99405829 14.41148891 11.12881978
  8.10946575  8.47100177  9.97739258  7.53436988 10.88137163  6.55164039
  9.64791444 12.40473915 11.22953058 10.09504927 10.26894394 11.34140578
  9.37904878 14.59207365  7.35211572 10.89650059 10.64171066 10.4848913
  7.52199345  9.40380953 11.25566651 14.98681104  8.73973231  4.20056502
  9.29134758 11.08511484  9.21934424  8.5751668  10.95912292 11.04019935
  9.98811084 11.0574915   8.86590718  9.04868082 10.6170462   9.49933274
 13.87247074 10.30569742  8.23617785 10.5217785   9.7538923  11.1632887
  7.29446289 10.55765714 11.59887001 10.7045396   9.65532608  9.98148036
  8.67554316 10.82498027  9.08913031  8.81238411  8.30575643  6.17871772
  8.09505434 12.08617169  4.94131837 11.43231196 10.20948073  9.57485726
 12.84031421 11.32493269 10.78086628  5.58671973 12.09714361  7.23924561
  8.33498065 11.05911807  9.87427133 11.43116863 11.28453188 10.08231925
  9.28237943  8.26986442 13.99157787 11.97277336 10.1

In [63]:

# 7. choice(a, size=None, replace=True, p=None) - Choix aléatoire
arr7_1 = np.random.choice([1, 2, 3, 4], size=10)  # 10 choix
arr7_2 = np.random.choice(5, size=3, replace=False)  # Sans remise
print(arr7_1)
print(arr7_2)


print()
# 8. shuffle(x) / permutation(x) - Mélange
arr8 = np.array([1, 2, 3, 4])
np.random.shuffle(arr8)  # Sur place
perm = np.random.permutation(arr8)  # Retourne nouvelle array
print(perm)


# 9. binomial(n, p, size=None) - Distribution binomiale
arr9 = np.random.binomial(10, 0.5, size=100)  # 100 tirages Binomial(10, 0.5)
print(arr9)

[1 2 1 4 3 3 1 1 2 1]
[2 3 0]

[3 4 1 2]
[5 4 5 7 5 5 1 5 3 4 9 4 7 6 4 3 3 6 5 5 4 3 5 6 7 4 4 4 3 3 5 4 6 3 5 1 8
 4 4 4 4 6 5 6 6 8 4 2 6 7 3 2 5 5 6 7 4 5 4 7 4 5 5 7 5 5 4 4 5 4 3 4 3 5
 4 6 8 2 5 6 8 3 4 5 5 2 4 6 4 6 5 5 5 4 7 3 1 6 6 5]


In [64]:

# 10. poisson(lam=1.0, size=None) - Distribution de Poisson
arr10 = np.random.poisson(5, size=50)  # Poisson(λ=5)
print(arr10)


print()
# 11. exponential(scale=1.0, size=None) - Distribution exponentielle
arr11 = np.random.exponential(2, size=100)  # β=2
print(arr11)


[ 4 11  2  6  5  5  4  6  6  5  7  6  3  5  2  7 10  1  7  6  3  3  5  6
  8  9  5  8  3  8  1  4  2  6  6  3  4  4  7  7  2 11  4  2  7  5  4  5
  1  5]

[2.67741467e+00 1.46634738e+00 2.15775820e+00 4.52395169e-01
 2.14506663e+00 3.75641969e-01 3.71659172e+00 3.68930895e-01
 1.26802198e+00 9.11821855e-01 2.86622538e-01 2.07565516e+00
 5.48515999e+00 6.48799557e-01 2.52793863e+00 1.53911283e+00
 3.96920025e+00 6.53338359e-02 7.78102067e-01 1.39186612e+00
 1.33496425e+00 4.92532175e-01 7.60105696e-01 2.75824670e+00
 6.20698038e-03 1.09456126e+00 1.94367317e+00 4.77025634e+00
 4.59816386e-01 1.69261285e+00 1.62282605e+00 1.23318782e+00
 9.13129825e-01 5.02623524e-02 8.97323617e-02 9.63178590e-01
 1.22164580e+00 2.15259556e+00 6.82722916e-01 2.48976579e+00
 3.20202121e-01 1.34107148e-01 1.55423224e-01 3.74129322e+00
 1.83948991e+00 3.71523805e+00 1.38957289e+00 1.16892877e+00
 1.65529499e+00 1.27186174e+00 2.13143915e-01 5.09139995e+00
 3.63267399e+00 8.54559997e+00 6.10741857e-01 6.1388

In [65]:
# 12. beta(a, b, size=None) - Distribution Beta
arr12 = np.random.beta(2, 5, size=50)
print(arr12)


print()
# 13. gamma(shape, scale=1.0, size=None) - Distribution Gamma
arr13 = np.random.gamma(2, 2, size=50)
print(arr13)

[0.1723616  0.13109256 0.01255701 0.27160004 0.29797621 0.27375062
 0.22406311 0.27616357 0.11798227 0.68515494 0.01593726 0.23996074
 0.50866665 0.11916934 0.19611128 0.1091321  0.2364436  0.20173774
 0.39988852 0.13878166 0.14806857 0.72083029 0.08549536 0.3570618
 0.03012664 0.19022386 0.37513938 0.71444325 0.53938047 0.16668811
 0.57984098 0.19433242 0.0721517  0.18303693 0.35675423 0.20740945
 0.57699239 0.17645671 0.12544831 0.14847886 0.58860451 0.53102763
 0.12339368 0.2308362  0.07100042 0.39530877 0.27170833 0.17886585
 0.340409   0.06118918]

[ 1.78112572  7.06849237  1.9171294   0.57260868  4.01628079  3.39689079
  3.81558087  0.83277424 12.98259203  4.14420325  1.21911846  3.58012732
  4.89223402  3.70610643  3.14703022  3.14427011  4.3398682   1.59242294
  2.82915363  5.02034202  4.94550943  3.23054374  5.80254254  9.57861729
  1.51465922  9.45210058  1.5959401   0.76045274  4.04729159  5.01103587
  5.21853719  2.88813033  0.12634765  0.69188947  6.47412113  3.09933081
  

### Nouvelle API NumPy (recommandée depuis 1.17)

In [66]:
# Créer un générateur
rng = np.random.default_rng(seed=42)

# Utiliser les méthodes
arr1 = rng.random((3, 3))      # Au lieu de np.random.rand()
print(arr1)

print()
arr2 = rng.standard_normal((3, 3))  # Au lieu de np.random.randn()
print(arr2)

print()
arr3 = rng.integers(0, 10, size=(3, 3))
print(arr3)

print()
arr4 = rng.normal(0, 1, size=50)
print(arr4)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]

[[-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826 ]]

[[8 8 2]
 [6 1 7]
 [7 3 0]]

[-0.15452948 -0.42832782 -0.35213355  0.53230919  0.36544406  0.41273261
  0.430821    2.1416476  -0.40641502 -0.51224273 -0.81377273  0.61597942
  1.12897229 -0.11394746 -0.84015648 -0.82448122  0.65059279  0.74325417
  0.54315427 -0.66550971  0.23216132  0.11668581  0.2186886   0.87142878
  0.22359555  0.67891356  0.06757907  0.2891194   0.63128823 -1.45715582
 -0.31967122 -0.47037265 -0.63887785 -0.27514225  1.49494131 -0.86583112
  0.96827835 -1.68286977 -0.33488503  0.16275307  0.58622233  0.71122658
  0.79334724 -0.34872507 -0.46235179  0.85797588 -0.19130432 -1.27568632
 -1.13328721 -0.91945229]


# ______________________________________________________________

## Partie 3 : Module secrets - pour la cryptographie

## 🔐 Partie 3 : Module secrets (cryptographie)

📌 Description

Le module secrets est conçu pour la sécurité.
Il génère des nombres aléatoires cryptographiquement sûrs.
il résiste aux attaques et convient aux mots de passe, jetons d'authentification, clés de chiffrement, etc.

✔️ Cas d’usage

- Mots de passe
- Tokens d’authentification
- Clés de sécurité

🔒 Avantage clé

- Résistant aux attaques (contrairement à random)



### 1. secrets.token_bytes(nbytes=None)

Génère des octets aléatoires sécurisés

In [67]:
import secrets

# Générer 16 octets (128 bits) pour une clé de chiffrement
key = secrets.token_bytes(16)
print(key)    # b'\x7f\xb4...' (bytes bruts)

# Usage typique : clé AES-128
from cryptography.fernet import Fernet
key = secrets.token_bytes(32)  # 256 bits pour AES-256
print(key)

b'rY\x9a\xb5B[q\xd9\xfe\xfe_\xfa\xfc\x07\x7fG'
b'lo\xb3\xf8\xf0\x987ob\xb2\xfbAn\xc6\r+5,\x15,Z\xceJ{\x12\x8eI\x01\xb0\x19\xb0-'


Pourquoi l'utiliser ?
Pour créer des clés de chiffrement ou des données binaires sensibles.

### 2. secrets.token_hex(nbytes=None)

Génère une chaîne hexadécimale sécurisée

In [68]:
# Générer 16 octets → 32 caractères hexadécimaux
token = secrets.token_hex(16)
print(token)  

# Cas d'usage : clé API, lien de réinitialisation de mot de passe
reset_link = f"https://monsite.com/reset?token={token}"

8c64545349c84c81c2889132fed68aae


Caractéristiques :

- Chaque octet donne 2 caractères hexadécimaux

- Taille prévisible (2 × nbytes)

- Facile à copier/coller ou stocker en base de données



### 3. secrets.token_urlsafe(nbytes=None)

Génère un token encodé en Base64 (compatible URL)

In [70]:
# Générer un token sans caractères problématiques (+/=)
token = secrets.token_urlsafe(16)
print(token)  

# Usage réel : jeton CSRF, session utilisateur
csrf_token = secrets.token_urlsafe(32)
print(csrf_token)

AikLgR3QvEk-qo8iZjK8zw
318ZXpQ-QH5omDEqQvXpz4ufaIOnmnshvRcbU2J3eXc


Avantage :

- Utilise l'alphabet A-Z, a-z, 0-9, - et _

- Pas de /, +, = qui doivent être encodés en URL

- Idéal pour les paramètres HTTP ou cookies

### 4. secrets.choice(sequence)

Choix aléatoire cryptographique

In [71]:
# Choisir un mot de passe simple parmi une liste
base = ['chien', 'chat', 'soleil', 'pluie']
mot = secrets.choice(base) + str(secrets.randbelow(100))
print(mot)  # "soleil42"


# Générer un caractère aléatoire
import string
alphabet = string.ascii_letters + string.digits
char = secrets.choice(alphabet)
print(char)

pluie90
B


Alternative à random.choice :

random.choice est **prévisible** → à ne **JAMAIS** utiliser pour la sécurité

### 5. secrets.randbelow(n)

Entier aléatoire entre 0 (inclus) et n (exclu)

In [72]:
# Nombre entre 0 et 99
num = secrets.randbelow(100)

# Générer un code à 6 chiffres (entre 100000 et 999999)
code = secrets.randbelow(900000) + 100000
print(code)


# Mot de passe avec chiffres
digits = ''.join(str(secrets.randbelow(10)) for _ in range(6))
print(digits)  # "483729"

991591
283371


Différence avec *random.randint* :

*secrets.randbelow* est **imprévisible** même si l'attaquant connaît la graine

### 6. secrets.compare_digest(a, b)

Comparaison sécurisée contre les attaques temporelles

In [ ]:
# ❌ MAUVAISE PRATIQUE (vulnérable à timing attack)
if motdepasse_saisi == motdepasse_stocke:
    print("OK")

# ✅ BONNE PRATIQUE (temps constant)
if secrets.compare_digest(motdepasse_saisi, motdepasse_stocke):
    print("OK")

# Exemple complet d'authentification
def verifier_motdepasse(entree, hash_stocke, sel):
    # ... vérification du hash ...
    return secrets.compare_digest(hash_calcule, hash_stocke)

### Tableau récapitulatif

In [ ]:
"""

Fonction	           Retour	                Usage typique	                    Résistance aux attaques

token_bytes	            bytes	                Clé de chiffrement	                  ✅ Cryptographique
token_hex	            str	                    Token lisible (stockage DB)	          ✅ Cryptographique  
token_urlsafe	        str	                    URL, cookies, paramètres HTTP	      ✅ Cryptographique
choice	                Élément	                Sélection sécurisée	                  ✅ Cryptographique           
randbelow		         int	                 Codes PIN, OTP                       ✅ Cryptographique
compare_digest		    bool	                Comparaison mdp/token                 ✅ Temps constant

 """


'\n\nFonction\t           Retour\t                Usage typique\t                    Résistance aux attaques\n\ntoken_bytes\t            bytes\t                Clé de chiffrement\t                  ✅ Cryptographique\ntoken_hex\t            str\t                    Token lisible (stockage DB)\t          ✅ Cryptographique  \ntoken_urlsafe\t        str\t                    URL, cookies, paramètres HTTP\t      ✅ Cryptographique\nchoice\t                Élément\t                Sélection sécurisée\t                  ✅ Cryptographique           \nrandbelow\t\t         int\t                 Codes PIN, OTP                       ✅ Cryptographique\ncompare_digest\t\t    bool\t                 Comparaison mdp/token                ✅ Temps constant\n\n '

### Piège à éviter ❌

In [ ]:
# NE PAS UTILISER random POUR LA SÉCURITÉ
import random
token = random.randint(0, 999999)  # PRÉVISIBLE !
print(token)

code = random.choice("0123456789")  # FAIBLE !
print(code)

18817
0


In [27]:
# TOUJOURS UTILISER secrets POUR LA SÉCURITÉ
import secrets
token = secrets.randbelow(1000000)  # SÉCURISÉ
print(token)

code = secrets.choice("0123456789") # SÉCURISÉ
print(code)

829150
9


## Exemple concret : générateur de mot de passe robuste

In [7]:
import secrets
import string

def generer_mdp(longueur=12):
    caracteres = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(caracteres) for _ in range(longueur))

# Générer 3 mots de passe forts
for _ in range(3):
    print(generer_mdp(16))


A%7jhv&EVCx#PRmP
!uM7t4i7vBVUfYlT
LFb2TR11CykiIlNq


## Exemple complet d'attaque par temporisation (Timing Attack)

Version 1

In [78]:

import time
import string
import statistics

# Alphabet 
ALPHABET = string.ascii_uppercase + string.ascii_lowercase + string.digits + string.punctuation  + "".join(chr(i) for i in range(0x00C0, 0x017F))
SECRET = "chien"

def mesurer_temps(guess, essais=5):
    mesures = []
    for _ in range(essais):
        start = time.perf_counter()
        insecure_compare(guess)
        end = time.perf_counter()
        mesures.append(end - start)
    return statistics.mean(mesures)

def attaque():
    prefix = ""
    
    print("🔓 Début de l'attaque...\n")
    
    for position in range(len(SECRET)):
        print(f"Position {position}...")

        meilleurs = []
        
        for c in ALPHABET:
            test = prefix + c
            t = mesurer_temps(test)
            meilleurs.append((t, c))
        
        # tri par temps décroissant
        meilleurs.sort(reverse=True)
        
        meilleur_char = meilleurs[0][1]
        prefix += meilleur_char
        
        print(f"➡️ Trouvé : {prefix}")
    
    print("\n✅ Mot de passe reconstruit :", prefix)

attaque()

🔓 Début de l'attaque...

Position 0...
➡️ Trouvé : c
Position 1...
➡️ Trouvé : cb
Position 2...
➡️ Trouvé : cbó
Position 3...
➡️ Trouvé : cbóÞ
Position 4...
➡️ Trouvé : cbóÞ5

✅ Mot de passe reconstruit : cbóÞ5


In [80]:
import time
import string
import statistics

SECRET = "SECRET"


def insecure_compare(user_input):
    for i in range(min(len(user_input), len(SECRET))):
        if user_input[i] != SECRET[i]:
            return False
        time.sleep(0.002)  # 2 ms par caractère correct (fuite volontaire)

    return len(user_input) == len(SECRET)



# Alphabet 
ALPHABET = string.ascii_uppercase + string.digits

def mesurer_temps(guess, essais=5):
    mesures = []
    for _ in range(essais):
        start = time.perf_counter()
        insecure_compare(guess)
        end = time.perf_counter()
        mesures.append(end - start)
    return statistics.mean(mesures)


def attaque():
    prefix = ""
    print("🔓 Début de l'attaque...\n")
    for position in range(len(SECRET)):
        print(f"Position {position}...")
        meilleurs = []
        for c in ALPHABET:
            test = prefix + c
            t = mesurer_temps(test)
            meilleurs.append((t, c))

        # tri par temps décroissant
        meilleurs.sort(reverse=True)
        meilleur_char = meilleurs[0][1]
        prefix += meilleur_char
        print(f"➡️ Trouvé : {prefix}")
    print("\n✅ Mot de passe reconstruit :", prefix)

attaque()

🔓 Début de l'attaque...

Position 0...
➡️ Trouvé : S
Position 1...
➡️ Trouvé : SE
Position 2...
➡️ Trouvé : SEC
Position 3...
➡️ Trouvé : SECR
Position 4...
➡️ Trouvé : SECRE
Position 5...
➡️ Trouvé : SECRET

✅ Mot de passe reconstruit : SECRET


version 2 : Plus robuste avec une fiabilité de 95 %

In [ ]:
import time
import string    #  pour générer l'alphabet 
import statistics    #  pour calculer la médiane des temps


SECRET = "Lamté"
     

# Fonction vulnérable (comparaison non sécurisée)
def insecure_compare(user_input):
    # Simulation d'une fuite temporelle de 2ms par caractère correct
    for i in range(min(len(user_input), len(SECRET))):
        if user_input[i] != SECRET[i]:
            return False
        time.sleep(0.002)  # Fuite volontaire de 2ms
    return len(user_input) == len(SECRET)


""" Explication :

Cette fonction compare l'entrée utilisateur avec un secret.
user_input : C'est la chaîne de caractères que l'attaquant propose pour tester.

____________
for i in range(min(len(user_input), len(SECRET))):

On boucle sur le plus petit des deux pour éviter de comparer au-delà de la longueur la plus courte.
Exemple concret :
SECRET = "ABC"  # longueur 3
user_input = "AB"  # longueur 2
min(2, 3) = 2  # On compare seulement les 2 premiers caractères
_______________

if user_input[i] != SECRET[i]:
            return False

            
- Compare caractère par caractère 
- Dès qu'un caractère est différent -> retourne False immédiatement
- Aucun délai pour ce cas (retour instantané)

Exemple : text

user_input = "AXC"
SECRET = "ABC"

i=0: 'A' vs 'A' → OK, continue
i=1: 'X' vs 'B' → DIFFÉRENT -> return False (instantané)

____________________________

 time.sleep(0.002)  # Fuite volontaire de 2ms

- time.sleep(0.002) : Pause de 2 millisecondes (0.002 secondes)
- C'est la vulnérabilité !
- On ne fait cette pause que si le caractère est correct
- Plus on a de caractères corrects, plus la fonction prend du temps

Visualisation : 

SECRET = "ABC"

"ABC" → ✅ 'A' (pause 2ms) → ✅ 'B' (pause 2ms) → ✅ 'C' (pause 2ms) → 6ms

"ABX" → ✅ 'A' (pause 2ms) → ✅ 'B' (pause 2ms) → ❌ 'X' ≠ 'C' → 4ms

"AXC" → ✅ 'A' (pause 2ms) → ❌ 'X' ≠ 'B' → 2ms

"XBC" → ❌ 'X' ≠ 'A' → 0ms

________________________________

return len(user_input) == len(SECRET)

- Si on a parcouru toute la boucle sans trouver d'erreur
- Alors on vérifie que les deux chaînes ont la même longueur
- Retourne True seulement si les deux sont identiques ET de même longueur


Exemples :
SECRET = "ABC"
user_input = "ABC"  → len(3) == len(3) → True ✅
user_input = "AB"   → len(2) == len(3) → False ❌ (mais on a déjà vérifié les 2 premiers)
user_input = "ABCD" → len(4) == len(3) → False ❌

______________________________

Le point clé à comprendre
L'attaquant peut mesurer le temps et en déduire combien de caractères sont corrects :

Temps ~0ms   → 0 caractère correct   → 1ère lettre fausse
Temps ~2ms   → 1 caractère correct   → 1ère lettre bonne, 2ème fausse
Temps ~4ms   → 2 caractères corrects → 1ère et 2ème bonnes, 3ème fausse
Temps ~6ms   → 3 caractères corrects → MOT DE PASSE COMPLET ! 🎯


________________________________

Que représente user_input ?
C'est la tentative de l'attaquant à chaque étape :

# Étape 1 : Deviner la 1ère lettre
insecure_compare("A")   # temps ~2ms → bonne !
insecure_compare("B")   # temps ~0ms → mauvaise
insecure_compare("C")   # temps ~0ms → mauvaise

# Étape 2 : Deviner la 2ème lettre (sachant que 1ère = 'A')
insecure_compare("AA")  # temps ~2ms → 2ème fausse
insecure_compare("AB")  # temps ~4ms → 2ème bonne ! (2 caractères corrects)
insecure_compare("AC")  # temps ~2ms → 2ème fausse

# Étape 3 : Deviner la 3ème lettre (sachant que début = 'AB')
insecure_compare("ABA") # temps ~4ms → 3ème fausse
insecure_compare("ABB") # temps ~4ms → 3ème fausse
insecure_compare("ABC") # temps ~6ms → 3ème bonne ! → mot de passe trouvé



C'est ainsi que l'attaquant reconstruit le mot de passe caractère par caractère !

"""




# --- Paramètres de l'attaque ---

# ALPHABET = string.ascii_uppercase + string.ascii_lowercase + string.digits 
ALPHABET = (
    string.ascii_uppercase +
    string.ascii_lowercase +
    string.digits +
    string.punctuation +
    "éèêëàâäùûüîïôöç" 
    # + "".join(chr(i) for i in range(0x00C0, 0x017F))   Plus complète(Unicode latin)
)

NB_ESSAIS = 15  # Nombre de mesures par caractère (plus c'est haut, plus c'est fiable)

def mesurer_temps_robuste(guess):
    mesures = []
    for _ in range(NB_ESSAIS):
        start = time.perf_counter()
        insecure_compare(guess)
        end = time.perf_counter()
        mesures.append(end - start)
        
    # On utilise la médiane pour ignorer les pics de lag du processeur
    return statistics.median(mesures)




""" Explication :

Role général : Cette fonction mesure plusieurs fois le temps de comparaison d'une tentative (guess) pour obtenir 
une mesure fiable et robuste au bruit du système.

guess : C'est la tentative que l'attaquant veut tester.
Exemple : "A", "AB", "ABC", etc.
guess = ce qu'on pense être le début du mot de passe


time.perf_counter() : Horloge de haute précision (microsecondes)

_________

insecure_compare(guess)

Exécute la fonction vulnérable avec la tentative guess
C'est là que le temps s'écoule (selon le nombre de caractères corrects)

__________

Exemple concret :
NB_ESSAIS = 3
guess = "AB"

Mesure 1 : start=100.000, end=100.004 → 0.004s (4ms) → mesures = [0.004]
Mesure 2 : start=100.010, end=100.014 → 0.004s → mesures = [0.004, 0.004]
Mesure 3 : start=100.020, end=100.025 → 0.005s (coup de processeur) → mesures = [0.004, 0.004, 0.005]

_______________

 return statistics.median(mesures)

- statistics.median() : Calcule la médiane des mesures
- La médiane = valeur du milieu quand on trie les temps

Pourquoi la médiane ?

Mesures(triées)	           Moyenne	                Médiane
[0.004, 0.004, 0.005]	   0.00433	                0.004

La médiane ignore les pics aberrants (quand le processeur est occupé ailleurs)


Exemple complet d'exécution :

SECRET = "ABC"
NB_ESSAIS = 3

# Test de "A"
print(mesurer_temps_robuste("A"))
# Mesure 1: 2ms
# Mesure 2: 2ms
# Mesure 3: 2ms
# → médiane = 2ms

# Test de "AB"  
print(mesurer_temps_robuste("AB"))
# Mesure 1: 4ms
# Mesure 2: 4ms
# Mesure 3: 15ms (coup de processeur)
# → médiane = 4ms (ignore le pic)

# Test de "ABC"
print(mesurer_temps_robuste("ABC"))
# Mesure 1: 6ms
# Mesure 2: 6ms
# Mesure 3: 6ms
# → médiane = 6ms



L'attaquant utilise cette fonction pour obtenir un temps fiable pour chaque guess, 
puis compare les temps pour deviner le bon caractère.

"""



def attaque_recursive(prefix=""):
    """
    Algorithme récursif avec backtracking pour garantir 95%+ de succès.
    """
    if len(prefix) == len(SECRET):
        # Vérification finale
        if insecure_compare(prefix):
            return prefix
        return None

    print(f"🔍 Recherche position {len(prefix)+1} (préfixe actuel: '{prefix}')")
    
    scores = []
    for c in ALPHABET:
        test = prefix + c
        t = mesurer_temps_robuste(test)
        scores.append((t, c))
    
    # On trie : les temps les plus longs en premier
    scores.sort(key=lambda x: x[0], reverse=True)

    # On teste les 3 meilleurs candidats (au cas où le 1er soit une erreur due au bruit)
    for i in range(3):
        candidat_char = scores[i][1]
        resultat = attaque_recursive(prefix + candidat_char)
        if resultat:
            return resultat
            
    return None




"""  Rôle général
Cette fonction reconstruit le mot de passe caractère par caractère en utilisant la récursivité et le backtracking.
Elle teste chaque caractère possible, mesure le temps, et continue avec les meilleurs candidats.

__________
def attaque_recursive(prefix=""):

prefix : La partie du mot de passe déjà découverte
Commence vide "", puis "A", puis "AB", etc.
C'est comme une accumulation des lettres trouvées
_____________

if len(prefix) == len(SECRET):
Condition d'arrêt : Quand le préfixe a la même longueur que le secret
Exemple : SECRET = "ABC" → on s'arrête quand len(prefix) = 3

_________________

if insecure_compare(prefix):
    return prefix
return None

Vérifie si prefix est le bon mot de passe

Si oui → retourne le mot de passe trouvé
Si non → retourne None (chemin invalide)


______________

scores = []
for c in ALPHABET:
    test = prefix + c
    t = mesurer_temps_robuste(test)
    scores.append((t, c))

    
Phase de test : On essaie TOUS les caractères de l'alphabet
Pour chaque caractère c, on construit test = prefix + c
On mesure le temps de réponse avec mesurer_temps_robuste(test)
On stocke le couple (temps, caractère) dans scores


Exemple avec prefix = "A" :
Text

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

Test "AA" → temps 2ms → scores.append((2, 'A'))
Test "AB" → temps 4ms → scores.append((4, 'B'))  ← plus long !
Test "AC" → temps 2ms → scores.append((2, 'C'))
...
Test "AZ" → temps 2ms → scores.append((2, 'Z'))
    
_____________
scores.sort(key=lambda x: x[0], reverse=True)

- Tri décroissant : Les temps les plus longs en premier
- lambda x: x[0] → on trie selon le premier élément du tuple (le temps)
- reverse=True → du plus grand au plus petit

Exemple de tri :
text
Avant tri : [(2,'A'), (4,'B'), (2,'C'), (1,'D')]
Après tri : [(4,'B'), (2,'A'), (2,'C'), (1,'D')]
→ 'B' est le meilleur candidat (temps le plus long)

_______________

for i in range(3):
    candidat_char = scores[i][1]
    resultat = attaque_recursive(prefix + candidat_char)
    if resultat:
        return resultat

Backtracking : On teste les 3 meilleurs candidats (et pas seulement le 1er)
Pourquoi 3 ? Pour gérer le bruit de mesure (parfois le 1er est faux à cause d'un pic CPU)
Pour chaque candidat, on appelle récursivement la fonction avec le nouveau préfixe
Si un chemin réussit (resultat n'est pas None), on le retourne


Arbre de recherche :

                    prefix = ""
                       |
            ┌──────────┼──────────┐
            |          |          |
         candidat1   candidat2   candidat3
            |          |          |
          "A"         "B"         "C"
            |          |          |
         ┌──┼──┐    ┌──┼──┐    ┌──┼──┐
         A  B  C    A  B  C    A  B  C
         |  |  |    |  |  |    |  |  |
        "AA" ...  "BA" ...  "CA" ...

____________

return None

Si aucun des 3 meilleurs candidats ne mène au mot de passe
Retourne None pour indiquer que ce chemin est un cul-de-sac


"""



# --- Exécution ---
print("="*50)
print("🔓 DÉBUT DE L'ATTAQUE TEMPORELLE HAUTE PRÉCISION")
print("="*50)

debut_total = time.time()
mot_de_passe_final = attaque_recursive()
fin_total = time.time()

if mot_de_passe_final:
    print("\n" + "="*50)
    print(f"✅ SUCCÈS : '{mot_de_passe_final}'")
    print(f"⏱️ Temps total : {fin_total - debut_total:.2f} secondes")
    print("="*50)
else:
    print("\n❌ Échec de la reconstruction.")

🔓 DÉBUT DE L'ATTAQUE TEMPORELLE HAUTE PRÉCISION
🔍 Recherche position 1 (préfixe actuel: '')
🔍 Recherche position 2 (préfixe actuel: 'L')
🔍 Recherche position 3 (préfixe actuel: 'La')
🔍 Recherche position 4 (préfixe actuel: 'Lam')
🔍 Recherche position 5 (préfixe actuel: 'Lamt')

✅ SUCCÈS : 'Lamté'
⏱️ Temps total : 43.87 secondes


### Pourquoi cette version est-elle "puissante" ?

Utilisation de *statistics.median* : La moyenne est polluée si ton antivirus ou Windows décide de travailler pendant une microseconde. La médiane, elle, reste stable car elle ignore les valeurs extrêmes.

*Backtracking (Récursion)* : C'est le secret des 95 %. Si le script se trompe au 3ème caractère à cause d'un ralentissement du PC, il ne va pas rester bloqué. Il va tester le "2ème meilleur choix" de la position précédente.

*Filtrage du Bruit* : Avec *NB_ESSAIS = 15*, on réduit statistiquement la probabilité d'erreur à un niveau quasi nul sur un délai de 2ms.

**Note pédagogique** : Dans un vrai système, la fuite est de l'ordre de la nanoseconde, pas de la milliseconde. Il faudrait alors des millions d'essais pour extraire le mot de passe, mais la logique mathématique resterait exactement la même !

# ___________________________________________________

🎯 Conclusion – Maîtriser l’Aléatoire en Python
<div align="center" style="background: linear-gradient(135deg, #1e3c72, #2a5298); padding: 30px; border-radius: 15px; color: white; margin: 30px 0;"> <h1 style="color: white; font-size: 2.2em; margin-bottom: 10px;">✨ Bien joué !</h1> <h2 style="color: #fbbf24; font-weight: 300; margin-top: 0;">Vous savez maintenant utiliser les bonnes méthodes aléatoires</h2> </div>
📊 Ce que vous avez appris
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 25px 0;"> <div style="background: #f0fdf4; padding: 20px; border-radius: 10px; border: 2px solid #86efac;"> <h3>🎲 random</h3> <ul> <li>✔️ Simple et rapide</li> <li>✔️ Idéal pour tests et simulations</li> <li>❌ Non sécurisé</li> </ul> </div> <div style="background: #eff6ff; padding: 20px; border-radius: 10px; border: 2px solid #60a5fa;"> <h3>📊 numpy.random</h3> <ul> <li>✔️ Performant</li> <li>✔️ Adapté aux tableaux</li> <li>✔️ Data science / ML</li> </ul> </div> <div style="background: #fef3c7; padding: 20px; border-radius: 10px; border: 2px solid #f59e0b;"> <h3>🔐 secrets</h3> <ul> <li>✔️ Sécurisé</li> <li>✔️ Mots de passe / tokens</li> <li>✔️ Cryptographie</li> </ul> </div> </div>
⚖️ L’essentiel à retenir
Utilisez random pour les besoins simples
Utilisez numpy.random pour les calculs intensifs
Utilisez secrets dès qu’il y a un enjeu de sécurité

👉 Le bon choix dépend toujours du contexte

💼 Applications concrètes
<div style="background: #f8fafc; padding: 20px; border-radius: 10px; margin: 20px 0;">
🎮 Jeux et simulations
📊 Data science et statistiques
🔐 Sécurité (authentification, tokens)
🤖 Machine learning
</div>
🏆 Bonnes pratiques
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 15px; margin: 25px 0;"> <div style="text-align: center; padding: 15px; background: #e0f2fe; border-radius: 10px;"> 🎯<br><strong>Choisissez le bon module</strong><br> Selon votre besoin </div> <div style="text-align: center; padding: 15px; background: #f0fdf4; border-radius: 10px;"> 🔒<br><strong>Sécurité d'abord</strong><br> Jamais `random` pour des mots de passe </div> <div style="text-align: center; padding: 15px; background: #fef3c7; border-radius: 10px;"> 🚀<br><strong>Optimisez</strong><br> Utilisez NumPy pour la performance </div> </div>
✨ Pour aller plus loin
Testez chaque module sur des cas concrets
Comparez leurs performances
Intégrez-les dans vos projets
<div align="center" style="margin-top: 40px; padding: 25px; background: linear-gradient(to right, #0f2027, #203a43, #2c5364); color: white; border-radius: 15px;"> <h2 style="color: white;">✨ Continuez à pratiquer ✨</h2> <p style="font-size: 1.05em; max-width: 700px; margin: 15px auto;"> L’aléatoire est un outil puissant.<br> Bien utilisé, il permet de simuler, sécuriser et modéliser efficacement. </p> <p style="font-size: 1.1em; font-weight: bold; color: #fbbf24;"> "Le hasard en programmation n’est jamais laissé au hasard." </p> </div>